apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp-deployment
  labels:
    app: scaletestapp
    prometheus-monitored: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
      - name: scaletestapp
        image: shestera/scaletestapp
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "15Mi"
            cpu: "200m"
          requests:
            memory: "15Mi"
            cpu: "100m" 
